name: 🐛 Bug report (Wallet)
description: Create a report to help us improve
# title: ""
labels: ["bug","wallet"]
assignees: ["dade-dd"]
body:        
  - type: dropdown
    id: env_wallet
    attributes:
      label: 어떤 지갑을 사용하였습니까?
      options:
        - Kaikas
        - Klip
        - Metamask
      multiple: false
    validations:
      required: true
      
  - type: input
    id: url
    attributes:
      label: 해당 이슈가 발생한 URL을 입력해주세요
      placeholder: "https://klaybay.io/games"
      
  - type: textarea
    id: detail
    attributes:
      label: 발견한 이슈사항을 적어주세요
      placeholder: "이미 고쳐졌을 수 있습니다. On a Mac 이라면 Shift+Command+R로 새로 고침후에 재시도해도 동일한 현상이 발생하는지 확인해주세요."
      

    

