name: π› Bug report
description: Create a report to help us improve
# title: ""
labels: ["bug"]
# assignees:
body:
  - type: markdown
    attributes:
      value: |
        (μ΄λ―Έ κ³ μ³μ΅μ„ μ μμµλ‹λ‹¤. On a Mac μ΄λΌλ©΄ Shift+Command+Rλ΅ μƒλ΅ κ³ μΉ¨ν›„μ— μ¬μ‹λ„ν•΄λ„ λ™μΌν• ν„μƒμ΄ λ°μƒν•λ”μ§€ ν™•μΈν•΄μ£Όμ„Έμ”.)
  - type: input
    id: env
    attributes:
      label: μ–΄λ–¤ ν™κ²½μ—μ„ ν™•μΈν•μ€μµλ‹κΉ?
      description: "μ‚¬μ©ν• λΈλΌμ°μ €μ™€ λΈλΌμ°μ €μ λ²„μ „μ„ μ μ–΄μ£Όμ„Έμ”. λ¨λ°”μΌμΌ κ²½μ° λ””λ°”μ΄μ¤ μ •λ³΄μ™€ λ””λ°”μ΄μ¤μ λ²„μ „λ„ μ μ–΄μ£Όμ‹κΈΈ λ°”λλ‹λ‹¤.(μ—¬λ ¤ν™κ²½μ• μ„ λ°κ²¬ν•μ€λ‹¤λ©΄ λ¨λ‘ μ μ–΄μ£Όμ„Έμ”)"
      placeholder: "IphoneSE2(14.8.1)"
      
  - type: checkboxes
    id: site
    attributes:
      label: μ–΄λ–¤ μ‚¬μ΄νΈμ—μ„ ν™•μΈν•μ€μµλ‹κΉ?
      options:
        - label: tmp
        - label: baobab
        - label: cypress
        
  - type: checkboxes
    id: wallet
    attributes:
      label: μ–΄λ–¤ μ§€κ°‘μ„ μ‚¬μ©ν•μ€μµλ‹κΉ?(μ§€κ°‘κ΄€λ ¨ μ΄μμΌ κ²½μ°)
      options:
        - label: Kaikas
        - label: Metamask
        - label: Klip
      

    

