name: π› Bug report
description: Create a report to help us improve
# title: ""
labels: ["bug"]
# assignees:
body:
  - type: markdown
    attributes:
      value: |
        (μ΄λ―Έ κ³ μ³μ΅μ„ μ μμµλ‹λ‹¤. On a Mac μ΄λΌλ©΄ Shift+Command+Rλ΅ μƒλ΅ κ³ μΉ¨ν›„μ— μ¬μ‹λ„ν•΄λ„ λ™μΌν• ν„μƒμ΄ λ°μƒν•λ”μ§€ ν™•μΈν•΄μ£Όμ„Έμ”.)
  - type: checkboxes
    id: site
    attributes:
      label: μ–΄λ–¤ μ‚¬μ΄νΈμ—μ„ ν™•μΈν–μµλ‹κΉ?
      options:
        - label: tmp
        - label: baobab
        - label: cypress
    

