name: 🐛 Bug report
description: Create a report to help us improve
# title: ""
labels: ["bug"]
# assignees:
body:        
  - type: dropdown
    id: env_browser
    attributes:
      label: 어떤 브라우저에서 테스트하였습니까?
      options:
        - Chrome
        - Safari
        - Firefox
      multiple: true
    validations:
      required: true
      
  - type: input
    id: url
    attributes:
      label: 해당 이슈가 발생한 URL을 입력해주세요
      placeholder: "https://klaybay.io/games"
      
  - type: textarea
    id: detail
    attributes:
      label: 발견한 이슈사항을 적어주세요
      placeholder: "이미 고쳐졌을 수 있습니다. On a Mac 이라면 Shift+Command+R로 새로 고침후에 재시도해도 동일한 현상이 발생하는지 확인해주세요."
      

    

