name: 🐛 Bug report
description: Create a report to help us improve
# title: ""
labels: ["bug"]
# assignees:
body:
  - type: markdown
    attributes:
      value: |
        (이미 고쳐졌을 수 있습니다. On a Mac 이라면 Shift+Command+R로 새로 고침후에 재시도해도 동일한 현상이 발생하는지 확인해주세요.)
  - type: input
    id: env
    attributes:
      label: 어떤 환경에서 확인하였습니까?
      description: "확인하였던 OS정보(모바일의 경우 디바이스정보)와 브라우저 정보를 입력해주세요\n
      여려 환경에서 발견한 경우 모두 적어주세요\n
      ex) MacOS-Chrome(103.0.5060.53) \nIphoneSE2(14.8.1)-Safari \nGalaxy S10+ -MetamaskBrowse(v5.9.1)"
      placeholder: "IphoneSE2(14.8.1)-MetamaskBrowse(v5.9.0)"
      
  - type: checkboxes
    id: site
    attributes:
      label: 어떤 사이트에서 확인하였습니까?
      options:
        - label: tmp
        - label: baobab
        - label: cypress
        
  - type: checkboxes
    id: wallet
    attributes:
      label: 어떤 지갑을 사용하였습니까?(지갑관련 이슈일 경우)
      options:
        - label: Kaikas
        - label: Metamask
        - label: Klip
      

    

