name: 🐛 Bug report
description: Create a report to help us improve
# title: ""
labels: ["bug"]
# assignees:
body:
  - type: markdown
    attributes:
      value: |
        (이미 고쳐졌을 수 있습니다. On a Mac 이라면 Shift+Command+R로 새로 고침후에 재시도해도 동일한 현상이 발생하는지 확인해주세요.)
  - type: checkboxes
    id: env_os
    attributes:
      label: 어떤 운영체제에서 테스트하였습니까?
      options:
        - label: MacOS
        - label: Window
        - label: Iphone
        - label: Android
        
  - type: input
    id: env_os_detail
    attributes:
      label: 모바일일 경우 디바이스 종류와 OS 버전을 명시해주세요
      description: "모바일일 경우 디바이스 종류와 OS 버전을 명시해주세요
      ex) IphoneSE2(14.8.1)\n
      Galaxy S10+"
      placeholder: "IphoneSE2(14.8.1),Galaxy S10+(10)"
      
  - type: checkboxes
    id: env_browser
    attributes:
      label: 어떤 브라우저에서 테스트하였습니까?
      description: 해당하는 버전이 없다면 아래 브라우저 버전 명시하는 폼에서 브라우저 정보를 함께 입력해주세요
      options:
        - label: Chrome
        - label: Safari
        - label: Firefox
        - label: Metamask browser
        - label: Kaikas browser
        
  - type: input
    id: env_browser_detail
    attributes:
      label: 브라우저의 버전을 명시해 주세요
      placeholder: "Chrome(103.0.5060.53)"
      
  - type: checkboxes
    id: site
    attributes:
      label: 어떤 사이트에서 확인하였습니까?
      options:
        - label: tmp
        - label: baobab
        - label: cypress
        
  - type: checkboxes
    id: wallet
    attributes:
      label: 어떤 지갑을 사용하였습니까?(지갑관련 이슈일 경우)
      options:
        - label: Kaikas
        - label: Metamask
        - label: Klip
      

    

