name: 💡 Feature request
description: Suggest an idea for this project
# title: ""
labels: ["bulb"]
# assignees:
body: 
  - type: textarea
    id: detail
    attributes:
      label: 발견한 이슈사항을 상세하게 적어주세요
      placeholder: "
Is your feature request related to a problem? Please describe.\n
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]\n
\n
Describe the solution you'd like\n
A clear and concise description of what you want to happen.\n
\n
Describe alternatives you've considered\n
A clear and concise description of any alternative solutions or features you've considered.
      "
      

    

