name: 🎨 Style related (Mobile)
description: Style
# title: ""
labels: ["art","mobile"]
assignees: ['skamiecho','dianneJung']
body:      
  - type: input
    id: env_os_detail
    attributes:
      label: 디바이스 종류와 브라우저 정보를 입력해주세요
      placeholder: "IphoneSE2-Safari"
        
  - type: input
    id: url
    attributes:
      label: 해당 이슈가 발생한 URL을 입력해주세요
      placeholder: "https://klaybay.io/games"
      
  - type: textarea
    id: detail
    attributes:
      label: 발견한 이슈사항을 상세하게 적어주세요
      placeholder: "이미 고쳐졌을 수 있습니다. On a Mac 이라면 Shift+Command+R로 새로 고침후에 재시도해도 동일한 현상이 발생하는지 확인해주세요."
      

    

